---
- name: Install Apache.
  hosts: all
  become: true    #Execute tasks with elevated privileges (eg: using sudo)

#Defining default variables
  vars:
    apache_package: apache2      
    apache_service: apache2

#Handlers are special tasks in Ansible that only run when explicitly triggered by anoter task like "notify: restart apache" mentioned below.
  handlers:
    - name: restart apache
      ansible.builtin.service:     #Ansible module for managing services, ensures correct command is used based on system it is runnng on, makes this playbook portable across Linux distros.
        name: "{{ apache_service }}"
        state: restarted

#Overrides variables if the OS is Red Hat.
  pre_tasks:
    - name: Override Apache vars for Red Hat.
      ansible.builtin.set_fact:
        apache_package: httpd
        apache_service: httpd
      when: ansible_os_family == 'RedHat'

#Installs the correct Apache package based on OS
  tasks:
    - name: Ensure Apache is installed.
      ansible.builtin.package:
        name: "{{ apache_package }}"
        state: present

    - name: Copy a web page.
      ansible.builtin.copy:
        content: |
          <html>
          <head><title>Hello world!</title></head>
          <body>Hello world!</body>
          </html>
        dest: "/var/www/html/index.html"
        mode: 0664
      notify: restart apache  #If the copy task finds that the file already matches the provided content, notify is NOT triggered, hence handler is not run (no change).

    - name: Ensure Apache is running and starts at boot.
      ansible.builtin.service:
        name: "{{ apache_service }}"
        state: started
        enabled: true
